export const AppConsts = {
    PageSize: 10,
    MaxPage: 5,
    OrderDecending: "ASC",
    PageSizeList: [5, 10, 20, 50],


    // Defend message - text in system:
    ConfirmDelete: "Do you want delete this item?",
    ConfirmDeleteSystem: "Are you sure you want to delete this system, this will be able to delete the pages, activities, permissions, ... of this system. Continue?",
    ConfirmSave: "Do you want save this changes?",
    ConfirmSyncUsers: "Do you want sync users into system?",
    Confirm: "Confirm",
    Update: "Update ",
    Create: "Create ",
    DeleteAll: "Delete all",
    Name: "Name",
    Description: "Description",
    IsActive: "Enabled",
    SearchPlaceHolder: "Input here to search...",
    Clone: "Clone",
    New: "New ",
    SaveChanges: "Save changes",
    RequiredError: "This field is required",
    GrantPermission: "Grant Permission",
    SystemKey: "System Key",
    SecretKey: "Secret Key",
    System: "System",
    Key: "Key",
    Role: "Role",
    Roles: "Roles",
    Username: "Username",
    RequiredIcon: '*',
    AssignRole: 'Assign Role',
    SyncUsers: 'Sync users',
    CreateSuccess: 'Create success',
    CreateFailure: 'Create failure: ',
    Success: 'Success',
    Failure: 'Failure',
    Error: 'Error',
    UpdateSuccess: 'Update success',
    UpdateFailure: 'Update failure: ',
    DeleteSuccess: 'Delete success',
    DeleteFailure: 'Delete failure',
    SyncUsersSuccess: 'Sync users success: ',
    SyncUsersFailure: 'Sync users failure',
    AssignRoleSuccess: 'Assign role success',
    AssignRoleFailure: 'Assign role failure',
    SaveChangeSuccess: 'Save change success',
    SaveChangeFailure: 'Save change failure',
    SaveChange:'Save Changes'
}

export const AppIcons = {
    Name: "fa fa-font",
    Description: "fa fa-align-center",
    Status: "fa fa-toggle-on",
    Permission: "fa fa-lock",
    Role: "fa fa-key",
    System: "fa fa-windows",
    Users: "fa fa-users",
    User: "fa fa-user",
    Group: "fa fa-group",
    Table: "fa fa-table",
    Page: "fa fa-file",
    Activity: "fa fa-plus",
    Add: "fa fa-plus",
    Save: "fa fa-plus",
    Edit: 'fa fa-edit',
    Remove: 'fa fa-trash',
    Clone: "fa fa-clone",
    Email: 'fa fa-envelope',
    Key: 'fa fa-key',
    SyncUsers: 'fa fa-sync',
    SaveChange:'fa fa-address-book-o',
    notify:'fa fa-bell'
}

